name: "00. Hello World"
run-name: "00. ${{ github.actor }}'s GitHub Actions Hello World 🚀"
on: [push, workflow_dispatch]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.actor is ${{ github.actor }}"
      - run: echo "github.event_name is ${{ github.event_name }}"
      - run: echo "runner.os is ${{ runner.os }}"
      - run: echo "github.ref is ${{ github.ref }}"
      - run: echo "github.repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}
      - run: echo "job.status is ${{ job.status }}."




















# More ons:
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

# on:
#   branch_protection_rule:
#     types: [created, deleted]

# When someone deletes a tag or branch
# on:
#   delete

# on:
#   discussion:
#     types: [answered, pinned, ...]

# More ons:
# fork, issues, registry_package, release, ...
