name: "03. Environment Variables"
run-name: "03. Environment Variables"
on: [push]

env:
  GLOBAL_VAR: hah

jobs:
  ci_env:
    runs-on: ubuntu-latest
    steps:
      - name: "CI env"
        run: echo "CI=$CI"

  custom_env:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: ouch
    steps:
      - run: echo "MY_VAR=$MY_VAR, GLOBAL_VAR=$GLOBAL_VAR, JOB_VAR=$JOB_VAR"
        env:
          MY_VAR: yaye
