name: "03. Environment Variables"
run-name: "03. Environment Variables"
on: [push]

jobs:
  ci_env:
    runs-on: ubuntu-latest
    steps:
      - name: "CI env"
        run: echo "CI=$CI"

  custom_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "MY_VAR=$MY_VAR"
        env:
          MY_VAR: yaye
