# Reusable Workflow:
name: "06. Inputs - Reusable Part"

# Other possibility:
# Composite Workflows by creating itenium-be/composite-action repository
# And "uses: itenium-be/composite-action@v1"

on:
  workflow_call:
    inputs:
      your_name:
        description: 'Greeting who?'
        required: true
        type: string
    secrets:
      PASS:
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ inputs.your_name }} in ${{ secrets.PASS }}!"
