name: "3. Environment Variables"
run-name: "3. Environment Variables"
on: [push]

jobs:
  ci_env:
    runs-on: ubuntu-latest
    steps:
      - name: "CI env"
        run: echo "CI=$CI"
        env:
          CI: true
