name: "4. Docker Container"
run-name: "4. Docker Container"
on: [push]

# As defined in:
# https://github.com/itenium-be/Github-Actions/settings/secrets/actions
env:
  THE_SECRET: '${{ secrets.THE_SECRET }}'
  OTHER: "ssh"

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - run: docker run busybox echo "Hello, World!"
      - run: echo "THE_SECRET=${{ env.THE_SECRET }}"
      - run: echo -n "${{ env.THE_SECRET }}" | xxd -ps
      - run: echo -n "${{ secrets.THE_SECRET }}" | xxd -ps

  build_img:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: ./docker
        run: docker build -t hello-world-busybox .
      - name: Run
        run: docker run -e THE_SECRET="${{ env.OTHER }}" hello-world-busybox
