name: "4. Docker Container"
run-name: "4. Docker Container"
on: [push]

env:
  WORLD: "World"

jobs:
  run-busybox:
    runs-on: ubuntu-latest
    steps:
      - run: docker run busybox echo "Hello, ${{ env.WORLD }}!"

  build_img:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: ./docker
        run: docker build -t hello-world-busybox .
      - name: Run
        run: docker run -e WORLD="${{ env.WORLD }}" hello-world-busybox
