name: "5. Secrets"
run-name: "5. Secrets"
on: [push]

# Secrets defined in:
# https://github.com/itenium-be/Github-Actions/settings/secrets/actions

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "secrets.txt"

    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"

    - name: Extract secret
      env:
        MY_VAL: ${{ secrets.THE_SECRET }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
