name: "5. Secrets"
run-name: "5. Secrets"
on: [push]

# Secrets defined in:
# https://github.com/itenium-be/Github-Actions/settings/secrets/actions

jobs:
  extract_secrets:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This is probably not the intention ;)"
    - name: "echo to file"
      env:
        SECRETS_VARS: ${{ toJson(secrets) }}
      run: echo "$SECRETS_VARS" > "secrets.txt"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecretsVariables
        path: "secrets.txt"

    - name: Extract secret
      env:
        MY_VAL: ${{ secrets.THE_SECRET }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python

  # real_usage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Log in to DockerHub
  #       uses: docker/login-action@v4
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build
  #       working-directory: ./docker
  #       run: docker build -t hello-world-busybox .
  #     - name: Tag
  #       run: docker tag hello-world-busybox ${{ secrets.DOCKER_USERNAME }}/hello-world-busybox:latest
  #     - name: Push
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-busybox:latest

# Usage:
# docker pull laoujin/hello-world-busybox
# docker run -e WORLD=itenium laoujin/hello-world-busybox

  # Or run it:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: laoujin/hello-world-busybox:latest
      options: --entrypoint "sh" -e WORLD=itenium
    steps:
      - name: Run a command in container
        run: echo "Hello $WORLD!"
      - name: List files in the root directory
        run: ls /
      - name: Print the environment variables
        run: env
