name: "8. .NET"
run-name: "8. .NET"
on: [push]

jobs:
  dot_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: DotNet Version
        run: dotnet --version
