name: "9. Issues"
run-name: "9. Issues"
on:
  issues:
    types:
      - reopened
      - opened

# Labels:
# https://github.com/itenium-be/Github-Actions/labels

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add CUSTOM label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: CUSTOM
